- name: play level variables
  hosts: local
  connection: local
  vars:
    course: ansible
    duration: 10HR
    lerner: malli

  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "courses name is: {{ course }}, duration: {{ duration }}, name: {{ lerner }}" 