- name: variables from promt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: what is your name?
    private: false
  - name: password
    prompt: what is your password?
    private: true
  
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello your username is: {{ username }}, password is: {{ password }}"