- name: variables form args
  hosts: local
  connection: local
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Hello yor course is : {{course}}, duration: {{ duration }}, learner is: {{ learner }}"