- name: loops
  hosts: local
  connection: local
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip